name: nvii_option_income
version: "1.0.0"
config-version: 2

profile: nvii_option_income

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests_dbt"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nvii_option_income:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
